azure/setup-kubectl@v2

diff --git a/.github/workflows/deploy--backend-auth.yml b/.github/workflows/deploy--backend-auth.yml
--- a/.github/workflows/deploy--backend-auth.yml
+++ b/.github/workflows/deploy--backend-auth.yml
@@ -44,20 +44,20 @@ jobs:
           tag=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ":" -f 2)
           echo "::set-output name=tag::$tag"
 
-      - name: Check if image exists
-        id: check-image
-        env:
-          IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
-        run: |
-          EXISTS=$(aws ecr describe-images --repository-name "${{ env.REPOSITORY_NAME }}" --image-ids imageTag="${{ env.IMAGE_TAG }}" --region ap-northeast-1)
-          if [ $? == 0 ]; then
-            echo "Image found: ${{ env.IMAGE_TAG }}"
-          else
-            echo "::error::Image does not exist. Stopping workflow."
-            exit 1
-          fi
+#      - name: Check if image exists
+#        id: check-image
+#        env:
+#          IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
+#        run: |
+#          EXISTS=$(aws ecr describe-images --repository-name "${{ env.REPOSITORY_NAME }}" --image-ids imageTag="${{ env.IMAGE_TAG }}" --region ap-northeast-1)
+#          if [ $? == 0 ]; then
+#            echo "Image found: ${{ env.IMAGE_TAG }}"
+#          else
+#            echo "::error::Image does not exist. Stopping workflow."
+#            exit 1
+#          fi
 
-      - uses: azure/setup-kubectl@v3
+      - uses: azure/setup-kubectl@v2
 
       - name: Create kubeconfig file
         run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}
